<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ougha.Trading.Core\Ougha.Trading.Core.csproj" />
    <ProjectReference Include="..\Ougha.Trading.Features\Ougha.Trading.Features.csproj" />
    <ProjectReference Include="..\Ougha.Trading.RL\Ougha.Trading.RL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
